"""Normalize SPPARKS text dumps without assuming site order or frame number = time."""
from pathlib import Path
import math


def read_energy(path):
    rows = []
    columns = None
    if not Path(path).exists():
        return rows
    for line in Path(path).read_text(errors='replace').splitlines():
        fields = line.split()
        if fields and fields[0] == 'Time' and 'Energy' in fields:
            columns = fields
        elif columns and len(fields) == len(columns):
            try:
                rows.append((float(fields[0]), float(fields[columns.index('Energy')])))
            except ValueError:
                pass
    return rows


def read_dump(path, log_path=None):
    lines = Path(path).read_text().splitlines()
    frames, ids, positions, bounds = [], None, None, None
    i = 0
    energies = read_energy(log_path) if log_path else []
    while i < len(lines):
        if not lines[i].strip():
            i += 1
            continue
        if lines[i] != 'ITEM: TIMESTEP':
            raise ValueError('Missing TIMESTEP header')
        stamp = lines[i + 1].split()
        time = float(stamp[-1])  # SPPARKS: snapshot index followed by model time.
        if lines[i + 2] not in ('ITEM: NUMBER OF ATOMS', 'ITEM: NUMBER OF SITES'):
            raise ValueError('Missing site count')
        n = int(lines[i + 3])
        if not lines[i + 4].startswith('ITEM: BOX BOUNDS'):
            raise ValueError('Missing bounds')
        frame_bounds = [[float(v) for v in lines[i + k].split()[:2]] for k in (5, 6, 7)]
        header = lines[i + 8].split()[2:]
        state_key = 'site' if 'site' in header else 'type'
        indices = [header.index(k) for k in ('id', 'x', 'y', 'z', state_key)]
        if i + 9 + n > len(lines):
            raise ValueError('Incomplete snapshot')
        rows = []
        for line in lines[i + 9:i + 9 + n]:
            parts = line.split()
            rows.append((int(parts[indices[0]]), *[float(parts[j]) for j in indices[1:4]], int(parts[indices[4]])))
        rows.sort(key=lambda row: row[0])
        frame_ids = [r[0] for r in rows]
        coords = [list(r[1:4]) for r in rows]
        if len(set(frame_ids)) != n or not all(math.isfinite(v) for p in coords for v in p):
            raise ValueError('Invalid site data')
        if ids is None:
            ids, positions, bounds = frame_ids, coords, frame_bounds
        elif frame_ids != ids or coords != positions or bounds != frame_bounds:
            raise ValueError('Only a fixed lattice is supported by this adapter')
        if frames and time <= frames[-1]['time']:
            raise ValueError('Snapshot times must increase')
        energy = next((e for t, e in energies if abs(t - time) < 0.025), None)
        frames.append({'time': time, 'states': [r[4] for r in rows], 'energy': energy})
        i += n + 9
    if not frames:
        raise ValueError('Empty dump')
    return {'schemaVersion': 1, 'modelId': 'potts', 'ids': ids, 'positions': positions,
            'bounds': bounds, 'spacing': 1, 'frames': frames}


def validate_parameters(raw):
    rules = {'size': (8, 32, 20, True), 'states': (2, 100, 100, True),
             'temperature': (0, 2, 0, False), 'seed': (1, 2147483646, 56789, True),
             'duration': (10, 100, 100, True)}
    if not isinstance(raw, dict) or set(raw) - set(rules):
        raise ValueError('参数字段不受支持')
    out = {}
    for key, (low, high, default, integer) in rules.items():
        value = raw.get(key, default)
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
            raise ValueError(f'{key} 必须是有限数值')
        if not low <= value <= high or (integer and int(value) != value):
            raise ValueError(f'{key} 必须在 {low}–{high} 范围内' + ('且为整数' if integer else ''))
        out[key] = int(value) if integer else value
    return out


def input_script(p):
    return f'''# Generated by SPPARKS Material Lab; fixed 3D periodic Potts template
seed {p['seed']}
app_style potts {p['states']}
dimension 3
boundary p p p
lattice sc/26n 1.0
region box block 0 {p['size']} 0 {p['size']} 0 {p['size']}
create_box box
create_sites box
set site range 1 {p['states']}
sweep random
sector yes
diag_style energy
temperature {p['temperature']}
stats {p['duration'] / 10:g}
dump 1 text {p['duration'] / 10:g} result.dump id site x y z
run {p['duration']}
'''
